spring:
  datasource:
    username: ${DATABASE_USERNAME:chat-app-user}
    password: ${DATABASE_PASSWORD:chat-app-password}
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/chat-app}
  messages:
    encoding: UTF-8
  jpa:
    database: POSTGRESQL
    database-platform: postgres
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: db/master-changelog.xml
    contexts: prod
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    protocol: ${SMTP_PROTOCOL:smtp}
    port: ${SMTP_PORT:587}
    properties:
      mail:
        smtp:
          auth: ${MAIL_AUTH:true}
          starttls:
            enable: ${MAIL_ENABLE:true}
    username: ${SMTP_USERNAME:chattapp741@gmail.com}
    password: ${SMTP_PASSWORD:jwomoksrujiensxp}
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
